const deploymentUrl = process.env.SITE_URL
  ? new URL(process.env.SITE_URL)
  : null;

export const site = {
  origin: deploymentUrl?.origin || "",
  basePath: deploymentUrl?.pathname.replace(/\/$/, "") || "",
  appId: "6809105741",
  name: "Human Turn",
};

export const sitePath = (path) => `${site.basePath}${path}`;

export const locales = {
  en: {
    name: "English",
    store: "us",
    storeLanguage: "en-US",
    features: "Features",
    privacy: "Privacy",
    download: "Get Human Turn",
    appStore: "View on Mac App Store",
    tour: "Take a closer look",
    eyebrow: "A quieter workflow. A native Mac app.",
    requirement: "For macOS 14 and later",
    integrations: "Your code sources. One place.",
    intro: "Less checking. More doing.",
    screenshots: "Right there in your menu bar.",
    screenshotKicker: "A closer look",
    tabs: [
      "Your next move",
      "Stay focused",
      "Connect your tools",
      "On-device intelligence",
    ],
    alts: [
      "Human Turn groups pull requests into Your turn, Waiting, and Unclear in the Mac menu bar.",
      "Human Turn item menu with snooze, mute repository, and ignore controls.",
      "Human Turn account connection screen for repositories and coding agents.",
      "Human Turn settings with optional on-device Apple Intelligence change summaries.",
    ],
    featureTitles: [
      "Your work, together.",
      "Come back at the right moment.",
      "Protect your focus.",
      "Your agent. Your workflow.",
      "Less reading. More context.",
      "At home on your Mac.",
      "Your work stays yours.",
    ],
    closing: "Know when it is your turn.",
    closingText:
      "Let the automated work carry on. Return when your code needs you.",
    language: "Language",
    navigation: "Main navigation",
    skip: "Skip to content",
    openImage: "Enlarge screenshot",
    close: "Close screenshot",
    back: "Back to Human Turn",
    privacyTitle: "Privacy, by design.",
    privacyIntro:
      "Human Turn runs locally on your Mac. Here is how it handles your information.",
    privacyHeadings: [
      "Connected services",
      "On-device summaries",
      "Your repositories",
      "This website",
    ],
    privacyWeb:
      "This website does not use analytics, advertising cookies, or third-party fonts. Your browser contacts the website host to load these pages and images. Following a Mac App Store link opens an Apple service, which has its own privacy policy.",
    rights: "Fortyone Agency LLC",
  },
  de: {
    name: "Deutsch",
    store: "de",
    storeLanguage: "de-DE",
    features: "Funktionen",
    privacy: "Datenschutz",
    download: "Human Turn laden",
    appStore: "Im Mac App Store ansehen",
    tour: "Die App entdecken",
    eyebrow: "Weniger Unterbrechungen. Eine native Mac-App.",
    requirement: "Für macOS 14 oder neuer",
    integrations: "Deine Codequellen. Ein Ort.",
    intro: "Weniger prüfen. Mehr schaffen.",
    screenshots: "Direkt in deiner Menüleiste.",
    screenshotKicker: "Ein genauerer Blick",
    tabs: [
      "Dein nächster Schritt",
      "Im Flow bleiben",
      "Tools verbinden",
      "KI auf deinem Mac",
    ],
    alts: [
      "Human Turn ordnet Pull Requests in der Mac-Menüleiste nach Du bist dran, Warten und Unklar.",
      "Human Turn mit Optionen zum Pausieren, Stummschalten eines Repositorys und Ignorieren.",
      "Human Turn verbindet Konten für Repositories und Coding-Agenten.",
      "Human Turn Einstellungen mit optionalen Apple Intelligence-Zusammenfassungen auf dem Gerät.",
    ],
    featureTitles: [
      "Deine Arbeit an einem Ort.",
      "Im richtigen Moment zurück.",
      "Bleib konzentriert.",
      "Dein Agent. Dein Workflow.",
      "Weniger lesen. Mehr Kontext.",
      "Auf deinem Mac zu Hause.",
      "Deine Arbeit bleibt deine.",
    ],
    closing: "Sieh, wann du dran bist.",
    closingText:
      "Lass die Automatisierung arbeiten. Kehre zurück, wenn dein Code dich braucht.",
    language: "Sprache",
    navigation: "Hauptnavigation",
    skip: "Zum Inhalt springen",
    openImage: "Screenshot vergrößern",
    close: "Screenshot schließen",
    back: "Zurück zu Human Turn",
    privacyTitle: "Datenschutz von Anfang an.",
    privacyIntro:
      "Human Turn läuft lokal auf deinem Mac. So geht die App mit deinen Daten um.",
    privacyHeadings: [
      "Verbundene Dienste",
      "Zusammenfassungen auf dem Gerät",
      "Deine Repositories",
      "Diese Website",
    ],
    privacyWeb:
      "Diese Website verwendet keine Analysedienste, Werbe-Cookies oder externen Schriftarten. Dein Browser verbindet sich mit dem Website-Host, um Seiten und Bilder zu laden. Links zum Mac App Store öffnen einen Dienst von Apple, für den eigene Datenschutzbestimmungen gelten.",
    rights: "Fortyone Agency LLC",
  },
  fr: {
    name: "Français",
    store: "fr",
    storeLanguage: "fr-FR",
    features: "Fonctionnalités",
    privacy: "Confidentialité",
    download: "Obtenir Human Turn",
    appStore: "Voir sur le Mac App Store",
    tour: "Découvrir l’app",
    eyebrow: "Moins d’interruptions. Une app Mac native.",
    requirement: "Pour macOS 14 ou ultérieur",
    integrations: "Vos sources de code. Un seul lieu.",
    intro: "Moins vérifier. Plus avancer.",
    screenshots: "Dans votre barre des menus.",
    screenshotKicker: "De plus près",
    tabs: [
      "Votre prochaine action",
      "Rester concentré",
      "Connecter vos outils",
      "L’intelligence sur votre Mac",
    ],
    alts: [
      "Human Turn classe les pull requests dans À vous, En attente et Indéterminé dans la barre des menus du Mac.",
      "Menu Human Turn avec report, mise en sourdine du dépôt et option pour ignorer un élément.",
      "Écran de connexion des comptes pour les dépôts et les agents de code dans Human Turn.",
      "Réglages Human Turn avec résumés facultatifs par Apple Intelligence sur l’appareil.",
    ],
    featureTitles: [
      "Votre travail, réuni.",
      "Revenez au bon moment.",
      "Gardez votre concentration.",
      "Votre agent. Votre méthode.",
      "Moins à lire. Plus de contexte.",
      "À sa place sur votre Mac.",
      "Votre travail reste le vôtre.",
    ],
    closing: "Sachez quand c’est à vous.",
    closingText:
      "Laissez l’automatisation avancer. Revenez quand votre code a besoin de vous.",
    language: "Langue",
    navigation: "Navigation principale",
    skip: "Aller au contenu",
    openImage: "Agrandir la capture",
    close: "Fermer la capture",
    back: "Retour à Human Turn",
    privacyTitle: "La confidentialité, dès la conception.",
    privacyIntro:
      "Human Turn fonctionne localement sur votre Mac. Voici comment vos informations sont traitées.",
    privacyHeadings: [
      "Services connectés",
      "Résumés sur l’appareil",
      "Vos dépôts",
      "Ce site web",
    ],
    privacyWeb:
      "Ce site n’utilise ni outils d’analyse, ni cookies publicitaires, ni polices tierces. Votre navigateur contacte l’hébergeur pour charger les pages et les images. Les liens vers le Mac App Store ouvrent un service Apple soumis à sa propre politique de confidentialité.",
    rights: "Fortyone Agency LLC",
  },
  es: {
    name: "Español",
    store: "es",
    storeLanguage: "es-ES",
    features: "Funciones",
    privacy: "Privacidad",
    download: "Obtener Human Turn",
    appStore: "Ver en el Mac App Store",
    tour: "Descubre la app",
    eyebrow: "Menos interrupciones. Una app nativa para Mac.",
    requirement: "Para macOS 14 o posterior",
    integrations: "Tus fuentes de código. Un lugar.",
    intro: "Menos comprobar. Más avanzar.",
    screenshots: "En tu barra de menús.",
    screenshotKicker: "Más de cerca",
    tabs: [
      "Tu siguiente paso",
      "Mantén la concentración",
      "Conecta tus herramientas",
      "Inteligencia en tu Mac",
    ],
    alts: [
      "Human Turn organiza las pull requests en Te toca, En espera e Indeterminado en la barra de menús del Mac.",
      "Menú de Human Turn con opciones para posponer, silenciar un repositorio e ignorar un elemento.",
      "Pantalla de conexión de cuentas para repositorios y agentes de código en Human Turn.",
      "Ajustes de Human Turn con resúmenes opcionales de Apple Intelligence en el dispositivo.",
    ],
    featureTitles: [
      "Tu trabajo, en un lugar.",
      "Vuelve en el momento justo.",
      "Mantén la concentración.",
      "Tu agente. Tu forma de trabajar.",
      "Menos lectura. Más contexto.",
      "Como en casa en tu Mac.",
      "Tu trabajo sigue siendo tuyo.",
    ],
    closing: "Sabe cuándo es tu turno.",
    closingText:
      "Deja que la automatización siga. Vuelve cuando tu código te necesite.",
    language: "Idioma",
    navigation: "Navegación principal",
    skip: "Ir al contenido",
    openImage: "Ampliar captura",
    close: "Cerrar captura",
    back: "Volver a Human Turn",
    privacyTitle: "Privacidad desde el diseño.",
    privacyIntro:
      "Human Turn funciona localmente en tu Mac. Así trata tu información.",
    privacyHeadings: [
      "Servicios conectados",
      "Resúmenes en el dispositivo",
      "Tus repositorios",
      "Este sitio web",
    ],
    privacyWeb:
      "Este sitio no utiliza herramientas de análisis, cookies publicitarias ni fuentes de terceros. Tu navegador contacta con el alojamiento del sitio para cargar las páginas e imágenes. Los enlaces al Mac App Store abren un servicio de Apple con su propia política de privacidad.",
    rights: "Fortyone Agency LLC",
  },
  ja: {
    name: "日本語",
    store: "jp",
    storeLanguage: "ja-JP",
    features: "機能",
    privacy: "プライバシー",
    download: "Human Turnを入手",
    appStore: "Mac App Storeで見る",
    tour: "アプリを見る",
    eyebrow: "作業を静かに見守る、Macネイティブアプリ。",
    requirement: "macOS 14以降に対応",
    integrations: "コードの接続先を、ひとつに。",
    intro: "確認を減らして、作業を前へ。",
    screenshots: "メニューバーで、ひと目でわかる。",
    screenshotKicker: "アプリを詳しく見る",
    tabs: ["次の一手", "集中を保つ", "ツールを接続", "Mac上のインテリジェンス"],
    alts: [
      "Macのメニューバーでプルリクエストを「あなたの番です」「待機中」「不明確」に分類するHuman Turn。",
      "スヌーズ、リポジトリのミュート、項目を無視する操作を表示したHuman Turnのメニュー。",
      "リポジトリとコーディングエージェントを接続するHuman Turnのアカウント画面。",
      "デバイス上のApple Intelligenceによる任意の変更要約を表示したHuman Turnの設定画面。",
    ],
    featureTitles: [
      "作業を、ひとつに。",
      "必要なタイミングで戻る。",
      "集中を、途切れさせない。",
      "いつものエージェントで。",
      "読む時間を短く。要点をすばやく。",
      "あなたのMacに、自然になじむ。",
      "あなたの作業は、あなたのもの。",
    ],
    closing: "あなたの出番を、見逃さない。",
    closingText:
      "自動化された作業は、そのまま進めて。コードにあなたが必要なときに戻りましょう。",
    language: "言語",
    navigation: "メインナビゲーション",
    skip: "本文へ移動",
    openImage: "スクリーンショットを拡大",
    close: "スクリーンショットを閉じる",
    back: "Human Turnに戻る",
    privacyTitle: "プライバシーに配慮した設計。",
    privacyIntro:
      "Human TurnはMac上でローカルに動作します。情報の取り扱いについてご説明します。",
    privacyHeadings: [
      "接続したサービス",
      "デバイス上の要約",
      "リポジトリ",
      "このウェブサイト",
    ],
    privacyWeb:
      "このサイトはアクセス解析、広告Cookie、外部フォントを使用しません。ページと画像の読み込みのため、ブラウザはサイトのホストに接続します。Mac App StoreへのリンクはAppleのサービスを開き、Apple独自のプライバシーポリシーが適用されます。",
    rights: "Fortyone Agency LLC",
  },
};

export const localePath = (locale) => (locale === "en" ? "/" : `/${locale}/`);
export const storeUrl = (locale) => {
  const { store, storeLanguage } = locales[locale];
  return `https://apps.apple.com/${store}/app/human-turn/id${site.appId}?l=${storeLanguage}&mt=12`;
};
